### ISSUE TITLE
Create Simple UART Loopback Program

### ISSUE THREAD

**Issue by kb1lqd** [FaradayRF/faradayio-firmware#20]
@kb1lqc needs a simple loopback program to test out the TUN network adapter.

This program should be super simple and just loop back bytes sent from RX to TX. This should not present a problem at 115200 baud but if bytes are being dropped then the baudrate should be slowed until byte buffers are added.

**Comment by kb1lqd** [comment]
@kb1lqc for awareness.

https://github.com/kb1lqd/faradayio-firmware/releases/tag/1

Per #20 a simple byte loopback program was created. This is for development ONLY. @kb1lqc should use this to have every byte sent to Faraday ECHO'd back to the host computer. Note that you should use Faraday BSL (Python 2.7) to load this into Faraday. I tested installing through BSL and the expected operation was successful.

The TI-TXT file for BSL loading is located https://github.com/kb1lqd/faradayio-firmware/blob/faraday_uart_loopback/Debug/faradayio.txt

You can also find it in this release in the folder Debug/faradayio.txt.

![image](https://user-images.githubusercontent.com/339144/36349542-55dd257a-143e-11e8-81bc-cdac7330d01a.png)

**Comment by kb1lqc** [comment]
Thanks for this @kb1lqd . I believe I am sending packets over serial to Faraday and seeing the echo data! I am at a odd spot where I can't use any standardized testing tools such as `ping`, `netperf`, `iperf`, etc. This is because none of these tools expect an echo'd response.

`ping` expects an [ECHO_REPLY](http://www.networksorcery.com/enp/protocol/icmp/msg0.htm)
* https://en.wikibooks.org/wiki/Communication_Networks/Ping

`netperf` and `iperf` both require servers to be at the other end of the sockets they use. This could be possible if I figure out how to map in software two TUNs together and run two of them but this seems obnoxious.
